name = "ZenCore"
uuid = "52727e99-4c58-4e84-9539-00d51bc68e7f"
authors = ["Li Huang <huangli@caep.cn>"]
version = "0.8.6"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Dates = "1.11.0"
Distributed = "1.11.0"
LinearAlgebra = "1.11.0"
Printf = "1.11.0"
TOML = "1.0.3"
